name: lab.axelerant
recipe: drupal9
config:
  webroot: web

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

proxy:
  phpmyadmin:
    - mysql.lab.axelerant.lndo.site

tooling:
  phpcs:
    service: appserver
    description: 'Run phpcs: lando phpcs'
    cmd:
      - 'phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md'
